# Generated by Django 3.1.2 on 2020-12-07 21:11

import MrMap.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20201207_2211'),
        ('service', '0002_auto_20201116_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[MrMap.validators.not_uuid])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=1000)),
                ('abstract', models.TextField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.mrmapgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('abstract', models.TextField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('folder', models.CharField(blank=True, max_length=1000, null=True)),
                ('index', models.IntegerField(default=0)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.mapcontext')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='WmsOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.layer')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.mapresource')),
            ],
        ),
    ]
